### ISSUE TITLE
The type or namespace name 'PostcodeNLDataAPI' could not be found

### ISSUE THREAD

**Issue by RudeySH** [RobThree/PostcodeNLDataAPI#1]
After installing the NuGet package, PostcodeNLDataAPI does not show up as a project reference. `using PostcodeNLDataAPI;` gives the following error:

```
The type or namespace name 'PostcodeNLDataAPI' could not be found
```

It appears the NuGet package is empty?

**Comment by RobThree** [comment]
Works fine for me? What kind of project is it? What .Net version? Anything else worth mentioning?

I just tested it with a new `Console Application` (.Net 4.6.2) and it installed fine, showed up as reference and I can use it.

**Comment by RudeySH** [comment]
I just tried it in a fresh ASP.NET MVC web application (.NET 4.6.2) and it worked fine. But it stops working after downgrading to .NET 4.5 and reinstalling the NuGet package.

What's the minimum supported .NET version for PostCodeNLDataAPI?

**Comment by RobThree** [comment]
I've only tested it on .Net 4.6.2. Will have to look to see what causes it to stop working on .Net 4.5. The package is [targeted at 4.6.2](https://github.com/RobThree/PostcodeNLDataAPI/blob/master/PostcodeNLDataAPI.nuspec#L30).

**Comment by RobThree** [comment]
We now support NetStandard 2.0
